dist: bionic
language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.10
    - otp_release: 22.0
      elixir: 1.11
    - otp_release: 23.0
      elixir: 1.9
    - otp_release: 23.0
      elixir: 1.10
    - otp_release: 23.0
      elixir: 1.11

cache:
  directories:
    - ~/.mix
    - ~/.hex
    - _build

